# Generated by Django 4.1 on 2022-08-08 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Comment_like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.post')),
            ],
        ),
    ]
